In [13]:
#Numpy
#concept about homogeneous multidimensional array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])#array created using numpy
print(arr)
#type
print(type(arr))
#dimension
print(arr.ndim)
#shape
print(arr.shape)
#no. of elements
print(arr.size)
#type of element
print(arr.dtype)
#create a new array of type float
a=np.array([[1,2,3],[4,5,6]],dtype='float')
print(a)
#create array from tuple
b=np.array((1,2,3))
print (b)
#3x4 array with all zeros
c=np.zeros((3,4))
print(c)
#array of complex number
d=np.full((3,3),6,dtype="float")
print(d)
#array of random values
r=np.random.random((2,2))
print(r)
#sequence of values from 0 t0 30 with interval of 5
f=np.arange(0,30,5)
print(f)
#sequence of 10 values in range 0 to 5
p=np.linspace(0,5,10)
print(p)
#reshape array
arr=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,0]])
n=arr.reshape(2,2,3)
print(n)
#array indexing
arr=np.array([[-1,2,0,4],[4,-0.5,6,2],[2.9,4,5,6],[1.2,5,0,3.5]])
print(arr)
#slicing
t=arr[:2,::2]
print(t)
#boolean array  indexing
cond=arr>0
t=arr[cond]
print(t)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
6
int32
[[1. 2. 3.]
 [4. 5. 6.]]
[1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
[[0.98567298 0.19505033]
 [0.123816   0.50224623]]
[ 0  5 10 15 20 25]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[[1 2 3]
  [4 4 5]]

 [[6 7 7]
  [8 9 0]]]
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   2. ]
 [ 2.9  4.   5.   6. ]
 [ 1.2  5.   0.   3.5]]
[[-1.  0.]
 [ 4.  6.]]
[2.  4.  4.  6.  2.  2.9 4.  5.  6.  1.2 5.  3.5]


In [19]:
#write a numpy to create a 3x3 matrix with values ranging from 2 to 10 
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [21]:
#flatten
import numpy as np
a=np.array([(1,2,3,4),(3,2,1,4)])
print(a.flatten())
#ravel
print(a.ravel())
# both gives same output
# both are convertion of 2D array to 1D array:
# flatten---returns copy of original array slower and method of ndarray element
# ravel---returns only reference of original array more faster, library level function

[1 2 3 4 3 2 1 4]
[1 2 3 4 3 2 1 4]


In [24]:
import numpy as np
#mathematical operators
#......unary operators.....
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a+1)
print(a-3)
print(a*10)
print(a**2)
print(a)
#transpose
print(a.T)

[[2 3 4 5]
 [6 7 8 9]]
[[-2 -1  0  1]
 [ 2  3  4  5]]
[[10 20 30 40]
 [50 60 70 80]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [29]:
import numpy as np
#built in operators
arr=np.array([[1,2,3],[4,5,6],[8,9,7]])
#maximum element
print(arr.max())
#rowwise maximum
print(arr.max(axis=1))
#column wise
print(arr.max(axis=0))
#minimum element
print(arr.min())
#rowwise minimum
print(arr.min(axis=1))
#column wise
print(arr.min(axis=0))
#sum of elements
print(arr.sum())

9
[3 6 9]
[8 9 7]
1
[1 4 7]
[1 2 3]
45


In [30]:
import numpy as np
#binary operators
a=np.array([[1,2],[4,5]])
b=np.array([[3,4],[5,6]])
#add
print(a+b)
#subtract
print(a-b)
#multiply of array
print(a*b)
#matrix multiplication
print(a.dot(b))

[[ 4  6]
 [ 9 11]]
[[-2 -2]
 [-1 -1]]
[[ 3  8]
 [20 30]]
[[13 16]
 [37 46]]


In [34]:
import numpy as np
#universal function
#array of sin value
n=np.array([0,np.pi/2,np.pi])
print(n)
print(np.sin(n))
#exponential values
a=np.array([0,1,2,3])
print(np.exp(a))
#square root
print(np.sqrt(a))
#sorting of array
a=np.array([[1,4,5],[2,8,1],[6,-1,3]])
print(np.sort(a,axis=1))
#sorting as per specification
print(np.sort(a,axis=1,kind='mergesort'))
#sorting of structured array
dtypes=[('name','S10'),('year',int),('cgpa',float)]
values=[('a',2008,9.5),('b',2010,8.9),('c',2009,5.6),('d',2010,9.6)]

print('the array is')
arr=np.array(values,dtype=dtypes)
print(arr)
print("after sort by names",np.sort(arr,order='name'))
print("after sort by year and cgpa",np.sort(arr,order=['year','cgpa']))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]
[[ 1  4  5]
 [ 1  2  8]
 [-1  3  6]]
[[ 1  4  5]
 [ 1  2  8]
 [-1  3  6]]
the array is
[(b'a', 2008, 9.5) (b'b', 2010, 8.9) (b'c', 2009, 5.6) (b'd', 2010, 9.6)]
after sort by names [(b'a', 2008, 9.5) (b'b', 2010, 8.9) (b'c', 2009, 5.6) (b'd', 2010, 9.6)]
after sort by year and cgpa [(b'a', 2008, 9.5) (b'c', 2009, 5.6) (b'b', 2010, 8.9) (b'd', 2010, 9.6)]


In [35]:
# create a numpy program of array ranging from 12 to 38
# create an array then reverse it
# convert an integer numpy array into float type
# write a numpy to append values at the end of array and show

In [36]:
import numpy as np
f=np.arange(12,39)
print(f)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [38]:
import numpy as np
f=np.arange(12,39)
print(f[::-1])

[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [39]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array(a,dtype='float')
a=b
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [46]:
import numpy as np
p=np.array([[1,2,3],[7,8,9]])
print(np.append(p,[4,5,6]))

[1 2 3 7 8 9 4 5 6]


In [48]:
import numpy as np
#character type
print(np.char.add(['xyz'],['hello']))
print(np.char.add(['hello','hi'],['welcome','bye']))
print(np.char.multiply('hello',3))
print(np.char.center('hello',20,fillchar='*'))
print(np.char.lower(['hello','world']))
print(np.char.upper(['hello','world']))

['xyzhello']
['hellowelcome' 'hibye']
hellohellohello
*******hello********
['hello' 'world']
['HELLO' 'WORLD']


In [58]:
#sparse matrix
import numpy as np
from numpy import array
from scipy.sparse import csr_matrix
matrix=np.array([[0,0],[0,1],[3,0]])
print(matrix)
sp=csr_matrix(matrix)
print(sp)

[[0 0]
 [0 1]
 [3 0]]
  (1, 1)	1
  (2, 0)	3


In [62]:
import numpy as np
#average,mean,standard deviation
matrix=np.array([[1,1,0],[2,5,1],[3,2,4]])
#mean
print(np.mean(matrix))
#median
print(np.median(matrix))
#Standard dev
print(np.std(matrix))

2.111111111111111
2.0
1.5234788000891208
